routes/admin.php
<?php

	Route::resource('movie','MovieController');	
	Route::get('movie/destroy/{id}', ['as' => 'movie/destroy', 'uses' => 'MovieController@destroy']);
	Route::post('movie/show', ['as' => 'movie/show', 'uses' => 'MovieController@show']);
	Route::post('movie/store', ['as' => 'movie/store', 'uses' => 'MovieController@store']);

	Route::resource('user','UserController');
	Route::get('user/destroy/{id}', ['as' => 'user/destroy', 'uses' => 'UserController@destroy']);
	Route::post('user/show', ['as' => 'user/show', 'uses' => 'UserController@show']);

routes/user.php
<?php

	Route::get('movie', ['uses' => 'MovieController@index']);

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
     return view('auth/login');
});

//Enrutamiento Peliculas 
Route::resource('movie','MovieController');
Route::post('movie/show',['as'=>'movie/show','uses'=>'MovieController@show']);
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Movie.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Movie extends Model
{
     protected $table = "movies";
    protected $fillable = ['name', 'description','category','user_id'];
    protected $guarded = ['id'];

    public function user()
    {
    	return $this->belongsTo('App\User');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name','lastname', 'email', 'password', 'document','role'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function movies()
    {
        return $this->hasMany('App\Models\Movie');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return redirect('movie');
    }
}

app/Http/Controllers/MovieController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Movie as Movie;

class MovieController extends Controller
{
     //Método cargar Lista de Peliculas
	public function index()
	{
		$movies=Movie::all();
		return \View::make('movies/list',compact('movies'));
	}
    //Método para cargar vista New en la carpeta movies
	public function create()
	{
		return \View::make('movies/new');
	}

    //Método Guardar Movie
    public function store(Request $request)
    {
    	 $request->validate([
            'name' =>'required|min:3|regex:/^[\pL\s\-]+$/u',
            'description' =>'required|min:6|regex:/^[\pL\s\-]+$/u'
        ]);
        $movie = new Movie;
        $movie->name = $request->name;
        $movie->description = $request->description;
        $movie->category=$request->category;
        $movie->user_id = \Auth::user()->id;
    	$movie->save();
    	return redirect('movie');
    }
    
    //Método para cargar vista Update en la carpeta movies
    public function edit($id)
    {
    	$movie = Movie::find($id);
    	return \View::make('movies/update',compact('movie'));
    }
    
     //Método Editar Movie
    public function update($id,Request $request)
    {
    	$movie = Movie::find($id);
    	$movie->name=$request->name;
    	$movie->description=$request->description;
        $movie->category=$request->category;
    	$movie->save();
    	return redirect('movie');

    }
    
    //Método para eliminar movie
    public function destroy($id) 
    {
        $movie = Movie::find($id);
        $movie->delete();
        return redirect()->back();
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;

class UserController extends Controller
{
    //Método cargar Lista de Usuarios
    public function index() {
        $users = User::all();
        return \View::make('users/list',compact('users'));
    }

    //Método para cargar vista Update en la carpeta users
    public function edit($id) {
        $user = User::find($id);
          
        return \View::make('users/update', compact('user'));
    }
    
    //Método para actualizar el usuario selecionado 
    public function update($id,Request $request)
    {
          $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'lastname'=>'required|string|max:255',
            'document'=>'required|string|max:255'
            
        ]);
          
        $user = User::find($id);
        $user->name=$request->name;
        $user->lastname=$request->lastname;
        $user->email=$request->email;
        $user->document=$request->document;
        $user->save();

        return redirect('admin/user');

    }


    public function destroy($id) 
    {
        $user = User::find($id);
        $user->delete();
        return redirect()->back();
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ ('SerieWeb') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">

                <a class="navbar-brand" href="{{ url('/') }}">
                    {{  ('Serie Web') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Iniciar sesión') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Registrate') }}</a>
                                </li>
                            @endif
                        @else
                         @if(\Auth::user()->role == 'Admin')
                                <li><a class="nav-link" href="{{ url('admin/movie') }}">Movie</a></li>
                            
                                <li><a class="nav-link" href="{{ url('admin/user') }}">User</a></li>
                            @endif
                            @if(\Auth::user()->role == 'User')
                                <li><a class="nav-link" href="{{ url('user/movie') }}">Movie</a></li>  
                            @endif
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Salir !') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
    <!-- The core Firebase JS SDK is always required and must be listed first -->
<script src="/__/firebase/7.9.3/firebase-app.js"></script>

<!-- TODO: Add SDKs for Firebase products that you want to use
     https://firebase.google.com/docs/web/setup#available-libraries -->
<script src="/__/firebase/7.9.3/firebase-analytics.js"></script>

<!-- Initialize Firebase -->
<script src="/__/firebase/init.js"></script>
</body>
</html>

resources/views/movies/list.blade.php
@extends('layouts.app')
@section('content')
  <section class="container">
  	 <div class="row">
  	 	 <article class="col-md-12">
        <div class="table-responsive">
  	 	 	<table class="table table-condensed table-striped table-bordered" >
  	 	 		<thead class="thead-dark">
  	 	 			<tr>
  	 	 				<th> Nombre </th>
  	 	 				<th> Descripcion </th>
              <th> Categoria </th>
  	 	 				<th> Accion  </th>
  	 	 			</tr>
  	 	 		</thead>
  	 	 		<tbody>
  	 	 			@foreach($movies as $movie)
  	 	 			  <tr>
  	 	 			     <td>{{$movie->name}}</td>
  	 	 			     <td>{{$movie->description}}</td>
                 <td>{{$movie->category}}</td>
  	 	 			     <td>
  	 	 			     	<a class="btn btn-primary btn-xs" href="{{ route('movie.edit',['id'=>$movie->id]) }}">Editar</a>
    	 			     	<a class="btn btn-danger btn-xs " href="{{ route('movie/destroy',['id' => $movie->id]) }}">Eliminar</a>
  	 	 			     </td>	
  	 	 			  </tr>
  	 	 			  @endforeach
  	 	 		</tbody>
  	 	 	</table>
        </div> 	 	
  	 	 </article>
         @if(\Auth::user()->role == 'Admin')
       <article class="col-md-12">
        {!! Form::open(['route'=>'movie.store','method'=>'post','novalidate','class'=>'form-inline']) !!} 
            
                <div class="ml-2">
                  <a href="{{ route('movie.create') }}" class="btn btn-primary">Create</a>  
                </div>          
        {!! Form::close() !!}
       </article>
       @endif
  	 </div>
  </section>
  @endsection

resources/views/movies/new.blade.php
@extends('layouts.app')
@section('content')
   <section class="container">
   	  <div class="row">
   	  	 <article class="col-md-10 col-md-offser-1">
   	  	 	{!! Form::open(['route'=>'movie.store','method'=>'post','novalidate']) !!}
   	  	 	<div class="form-group">
   	  	 		<label>Nombre</label>
   	  	 		<input type="text" name="name" class="form-control" required>
   	  	 	</div>
   	  	 	<div class="form-group">
   	  	 		<label>Descripcion</label>
   	  	 		<input type="text" name="description" class="form-control" required>
   	  	 	</div>
             <div class="form-group row">
                            <label class="col-md-4 col-form-label text-md-right">Categoria</label>
                            <div class="col-md-6">
                                <select name="category" class="col-md-12 form-control">
                                    <option value="">Seleccione</option>
                                    <option value="Serie">Serie</option>
                                    <option value="Pelicula">Pelicula</option>                                    
                                </select>
                            </div>
                        </div>
   	  	 	<div class="form-group">
   	  	 		<button type="submit" class="btn btn-success">Enviar</button>
   	  	 	</div>
   	  	 	{!! Form::close() !!}
   	  	 </article>
   	  </div>
   </section>
@endsection   

resources/views/movies/update.blade.php
@extends('layouts.app')
@section('content')
   <section class="container">
   	  <div class="row">
   	  	 <article class="col-md-10 col-md-offser-1">
   	  	 	{!! Form::model($movie,['route'=>['movie.update',$movie->id],'method'=>'put','novalidate']) !!}
   	  	 	<div class="form-group">
   	  	 		<label>Nombre</label>
   	  	 		<input type="text" name="name" class="form-control" required value="{{ $movie->name }}">
   	  	 	</div>
   	  	 	<div class="form-group">
   	  	 		<label>Descripcion</label>
   	  	 		<input type="text" name="description" class="form-control" required value="{{ $movie->description }}">
   	  	 	</div>
   	  	 	<div class="form-group">
   	  	 		<button type="submit" class="btn btn-success">Enviar</button>
   	  	 	</div>
   	  	 	{!! Form::close() !!}
   	  	 </article>
   	  </div>
   </section>
@endsection  

resources/views/users/list.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">			
			<article class="col-md-12">
				<div class="table-responsive">
				<table class="table table-condensed table-striped table-bordered">
					<thead class="thead-dark">
						<tr>
							<th>Apellido</th>
							<th>Nombre</th>
							<th>Email</th>
							<th>Documento</th>
							<th>Action</th>
						</tr>
					</thead>
					<tbody>						
						@foreach($users as $user)
							<tr>
								<td>{{ $user->lastname }}</td>
								<td>{{ $user->name }}</td>
								<td>{{ $user->email }}</td>
								<td>{{ $user->document }}</td>
								<td>
									<a class="btn btn-primary btn-xs" href="{{ route('user.edit',['id' => $user->id]) }}">Editar</a>
									<a class="btn btn-danger btn-xs" href="{{ route('user/destroy',['id' => $user->id]) }}">Eliminar</a>
								</td>
							</tr>
						@endforeach
					</tbody>
				</table>
				</div>
			</article>
		</div>
	</section>
@endsection

resources/views/users/update.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-10 col-md-offset-1">
				{!! Form::model($user,['route' => ['user.update', $user->id], 'method' => 'put', 'novalidate']) !!}
					<div class="form-group">
						<label>Nombre</label>
						<input type="text" name="name" class="form-control" required value="{{ $user->name }}">
					</div>
					<div class="form-group">
						<label>Apellido</label>
						<input type="text" name="lastname" class="form-control" required value="{{ $user->lastname }}">
					</div>
					<div class="form-group">
						<label>Email</label>
						<input type="email" name="email" class="form-control" required value="{{ $user->email }}">
					</div>
					<div class="form-group">
						<label>Documento</label>
						<input type="text" name="document" class="form-control" required value="{{ $user->document }}">
					</div>
					
					<div class="form-group">
						<button type="submit" class="btn btn-success">Enviar</button>
					</div>
				{!! Form::close() !!}
			</article>
		</div>	
	</section>
@endsection